"use strict";
const $ = id => document.getElementById(id);
const names = {"prerequisites.install":"Install tool prerequisites",capabilities:"Worker capabilities",posture:"Security posture","services.list":"List services","service.control":"Manage service","processes.list":"List processes","process.stop":"Terminate process","files.list":"Browse folder","files.read":"Download file","files.write":"Upload file","logs.read":"Collect event logs","reboot.status":"Restart readiness","reboot":"Schedule restart","packages.list":"Installed software","package.install":"Install package","package.remove":"Remove package","patches.scan":"Scan for updates","patches.install":"Install updates","encryption.status":"Disk encryption status","bitlocker.escrow":"Escrow BitLocker recovery keys","recovery.rotate":"Rotate emergency administrator","isolation.start":"Temporarily isolate device","isolation.release":"Release isolation","script.run":"Run reviewed script","shell.start":settings.platform==="windows"?"Open SYSTEM PowerShell":"Open root terminal","update.install":"Install signed component update"};
const numbers = new Set(["pid","since","limit","delay","hours","seconds","columns","rows"]);
const defaults = {operation:"restart",channel:settings.platform==="windows"?"System":"journal",since:60,limit:100,delay:60,hours:24,seconds:120,columns:100,rows:30,inputs:"{}",component:"agent",path:settings.platform==="windows"?"C:\\NorthGateRMM-Ops":"/var/lib/NorthGateRMM-Ops"};
let shell=null,after=0,inputSequence=0,stopped=false,busy=false,inputBusy=false,workerReady=false;
let inputQueue=[];
const terminal=new Terminal({cols:100,rows:30,scrollback:2000,convertEol:false,allowProposedApi:false,theme:{background:"#101828"}});
terminal.open($("terminal-output"));
// Remote output cannot write the operator's clipboard.
terminal.parser.registerOscHandler(52,()=>true);
function queueInput(input){if(!shell)return;if(inputQueue.length>=64){message("Terminal input queue full; wait for the worker");return;}inputQueue.push({input,sequence:++inputSequence});}
terminal.onData(data=>queueInput({data:b64(new TextEncoder().encode(data))}));
function resizeTerminal(){const cols=Math.max(20,Math.min(240,Math.floor(($("terminal-output").clientWidth-24)/9)));terminal.resize(cols,30);queueInput({columns:cols,rows:30});}
window.addEventListener("resize",resizeTerminal);
function message(text){$("message").textContent=text;}
async function call(path,body){const response=await fetch(settings.base+path,{method:body?"POST":"GET",headers:body?{"Content-Type":"application/json"}:{},body:body?JSON.stringify({...body,csrf:settings.csrf}):undefined,cache:"no-store",redirect:"error"});if(!response.ok)throw new Error((await response.text()).slice(0,500));return response.json();}
for(const action of Object.keys(settings.actions)){if((action==="bitlocker.escrow"&&settings.platform!=="windows")||(["bitlocker.escrow","recovery.rotate"].includes(action)&&!settings.recovery))continue;const option=document.createElement("option");option.value=action;option.textContent=names[action]||action;$("operation").append(option);}
function form(){const action=$("operation").value;$("parameters").replaceChildren();for(const key of settings.actions[action]){if(action==="files.write"&&["data","sha256"].includes(key))continue;const label=document.createElement("label");label.textContent=key.replaceAll("_"," ")+" ";const input=document.createElement(key==="inputs"?"textarea":"input");input.name=key;if(numbers.has(key))input.type="number";else if(key==="overwrite")input.type="checkbox";input.value=defaults[key]??"";label.append(input);$("parameters").append(label,document.createElement("br"));}if(action==="files.write"){const file=document.createElement("input");file.type="file";file.name="upload";$("parameters").append(file);}}
$("operation").addEventListener("change",form);form();
function b64(bytes){let value="";for(let i=0;i<bytes.length;i+=8192)value+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(value);}
function bytes(value){return Uint8Array.from(atob(value),c=>c.charCodeAt(0));}
async function run(){if(busy||!workerReady){message("Wait for the privileged worker to become ready");return;}busy=true;$("run").disabled=true;try{const action=$("operation").value,params={};for(const input of $("parameters").elements){if(!input.name||input.name==="upload")continue;params[input.name]=input.type==="checkbox"?input.checked:numbers.has(input.name)?Number(input.value):input.name==="inputs"?JSON.parse(input.value):input.value;}if(action==="files.write"){const file=$("parameters").elements.upload.files[0];if(!file||file.size>15*1024*1024)throw new Error("Choose a file up to 15 MiB");const data=new Uint8Array(await file.arrayBuffer());params.data=b64(data);params.sha256=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",data)),n=>n.toString(16).padStart(2,"0")).join("");}
 const result=await call("/action",{action,params,exercise:$("exercise").value});message("Job queued: "+result.job);if(action==="shell.start"){shell=result.job;after=0;inputSequence=0;inputQueue=[];terminal.reset();resizeTerminal();terminal.focus();$("terminal-state").textContent="Connecting privileged terminal…";await terminalPoll();}await refresh();
}catch(error){message(error.message);}finally{busy=false;$("run").disabled=!workerReady;}}
$("run").addEventListener("click",run);
async function cancel(job){await call("/action",{action:"cancel",job});if(job===shell){shell=null;$("terminal-state").textContent="Disconnect requested";}await refresh();}
function download(name,data){const url=URL.createObjectURL(new Blob([data],{type:"application/octet-stream"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
async function downloadFile(job,file){const response=await fetch(settings.base+"/download",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({job,csrf:settings.csrf}),cache:"no-store",redirect:"error"});if(!response.ok)throw new Error("Download authorization or integrity failed");const raw=new Uint8Array(await response.arrayBuffer());const hash=Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",raw)),v=>v.toString(16).padStart(2,"0")).join("");if(hash!==file.sha256||hash!==response.headers.get("X-Content-SHA256")||raw.length!==file.size)throw new Error("Download integrity failed");download(file.name,raw);}
function button(text,action){const b=document.createElement("button");b.type="button";b.textContent=text;b.addEventListener("click",()=>action().catch(e=>message(e.message)));return b;}
async function refresh(){const data=await call("/state");workerReady=!!data.worker.ready;$("run").disabled=busy||!workerReady;$("capabilities").textContent=JSON.stringify(data.worker.capabilities||{},null,2);const expanded=new Set(Array.from($("jobs").querySelectorAll("details[open]"),n=>n.dataset.job));$("readiness").textContent=data.worker.ready?"Worker ready · "+data.worker.capabilities.execution_identity+" · "+data.worker.capabilities.version:data.worker.reason||"Privileged worker is offline";const nodes=[];
 for(const job of data.jobs){const row=document.createElement("details"),summary=document.createElement("summary");summary.textContent=(names[job.action]||job.action)+" · "+job.state+" · "+new Date(job.created*1000).toLocaleString();row.dataset.job=job.id;row.open=expanded.has(job.id);row.append(summary);const meta=document.createElement("p");meta.textContent="Job "+job.id+(job.exercise?" · Exercise "+job.exercise:"");row.append(meta);if(job.restart_verification){const status=document.createElement("p");status.textContent=job.restart_verification;row.append(status);}if(!["completed","failed","cancelled","expired","result_unknown"].includes(job.state))row.append(button("Cancel",()=>cancel(job.id)));
  if(job.secret_result){if(job.state==="completed"&&settings.recovery)row.append(button("Reveal recovery result",async()=>{const result=await call("/reveal",{job:job.id});const text=document.createElement("pre");text.textContent=result.output;row.append(text);setTimeout(()=>text.remove(),30000);}));}
  else if(job.receipt){const pre=document.createElement("pre");pre.textContent=job.receipt.error||job.receipt.output;row.append(pre);if(job.action==="files.read"&&job.state==="completed"){try{const file=JSON.parse(job.receipt.output);pre.textContent=file.name+" · "+file.size+" bytes · SHA-256 "+file.sha256;row.append(button("Download",()=>downloadFile(job.id,file)));}catch{pre.textContent="Invalid file result";}}}
  nodes.push(row);
 }$("jobs").replaceChildren(...nodes);
}
async function terminalRequest(){if(!shell)return;const job=shell,pending=inputQueue[0];const result=await call("/io",{job,after,...pending});if(shell!==job)return;if(pending)inputQueue.shift();for(const frame of result.frames){if(frame.sequence<=after)continue;terminal.write(bytes(frame.value.data));after=frame.sequence;}$("terminal-state").textContent=result.state;if(["completed","failed","cancelled","expired","result_unknown"].includes(result.state)&&result.frames.length<32){shell=null;inputQueue=[];}}
async function terminalPoll(){if(!shell||inputBusy)return;inputBusy=true;try{await terminalRequest();}catch(error){message(error.message);}finally{inputBusy=false;}}
$("terminal-form").addEventListener("submit",event=>{event.preventDefault();queueInput({data:b64(new TextEncoder().encode($("terminal-input").value+"\r"))});$("terminal-input").value="";});
$("interrupt").addEventListener("click",()=>queueInput({data:btoa("\x03")}));
$("disconnect").addEventListener("click",()=>shell&&cancel(shell).catch(e=>message(e.message)));
$("publish-script").addEventListener("click",async()=>{try{const result=await call("/scripts",{content:$("script-content").value,inputs:$("script-inputs").value.split(",").map(s=>s.trim()).filter(Boolean)});message("Saved script "+result.script_id+" at version "+result.version);}catch(error){message(error.message);}});
async function loop(){if(stopped)return;try{await terminalPoll();if(!shell)await refresh();}catch(error){message(error.message);}setTimeout(loop,shell?500:5000);}
window.addEventListener("pagehide",()=>{stopped=true;});loop();
$("load-infrastructure").addEventListener("click",async()=>{try{$("infrastructure").textContent=JSON.stringify(await call("/infrastructure"),null,2);}catch(e){message(e.message);}});
$("save-infrastructure").addEventListener("click",async()=>{try{await call("/infrastructure",{});message("Infrastructure baseline saved");}catch(e){message(e.message);}});
$("link-capture").addEventListener("click",async()=>{try{await call("/capture-evidence",{capture:$("capture-id").value,exercise:$("exercise").value});message("Capture linked to exercise");}catch(e){message(e.message);}});
$("load-releases").addEventListener("click",async()=>{try{const result=await call("/catalog");$("releases").replaceChildren(...result.releases.map(release=>button(release.manifest.component+" · "+release.manifest.version,async()=>{$("operation").value="update.install";form();const values={...release.manifest,url:release.url,signature:release.signature};for(const input of $("parameters").elements)if(input.name in values)input.value=values[input.name];message("Release selected. Run operation to deploy to this endpoint.");})));}catch(e){message(e.message);}});
