"use strict";
const q=id=>document.getElementById(id), base=location.pathname.replace(/\/ui$/, ""), kinds={rdp:["username","password","domain"],ssh:["username","private-key","passphrase"],api:["token"],recovery:["key"]};
let state=null,busy=false,revealTimer=null,offset=0;
const el=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
function hide(){clearTimeout(revealTimer);q("revealed").textContent="";q("reveal").hidden=true;}
document.addEventListener("visibilitychange",()=>{if(document.hidden)hide();});window.addEventListener("pagehide",hide);q("hide").onclick=hide;
function message(text){q("message").textContent=text;}
async function load(){const r=await fetch(base+"/state?offset="+offset,{cache:"no-store"});if(!r.ok)throw Error(await r.text());state=await r.json();render();renderPages();renderRecovery();}
function renderRecovery(){q("import-card").hidden=!state.recovery_import_available;q("recovery-job").replaceChildren();for(const job of state.recovery_jobs){const option=el("option",`${job.action==="bitlocker.escrow"?"BitLocker escrow":"Emergency account"} · ${new Date(job.created*1000).toLocaleString()} · ${job.id.slice(0,8)}`);option.value=job.id;q("recovery-job").append(option);}q("import-empty").hidden=Boolean(state.recovery_jobs.length);q("import-form").hidden=!state.recovery_jobs.length;}
function renderPages(){q("pages").replaceChildren();q("pages").append(el("span",`${state.total} credentials · ${state.records.length?state.offset+1:0}–${state.offset+state.records.length}`));if(state.offset>0)q("pages").append(button("Previous",()=>page(Math.max(0,state.offset-20))));if(state.next_offset!==null)q("pages").append(button("Next",()=>page(state.next_offset)));}
async function page(value){if(busy)return;clearEditor();hide();offset=value;try{await load();}catch(e){message(e.message);}}
function button(text,fn){const n=el("button",text);n.type="button";n.onclick=fn;n.disabled=busy;return n;}
function render(){q("health").textContent=state.health.initialized&&!state.health.sealed?"OpenBao is ready":"OpenBao is unavailable, sealed or not initialized. Credential actions require a healthy provider.";q("add").hidden=!state.permissions.includes("admin");q("records").replaceChildren();for(const record of state.records){const row=el("div");row.className="record";row.append(el("strong",record.label),el("small",`${record.kind.toUpperCase()} · ${record.retired?"Retired":record.use_for_remote?"Used for browser connections":"Stored credential"} · ${record.available?"Version "+record.current_version:"Provider unavailable"}`));const actions=el("div");actions.className="actions";if(state.permissions.includes("reveal")&&!record.retired)actions.append(button("Reveal briefly",()=>reveal(record)));if(state.permissions.includes("admin")){actions.append(button("Manage",()=>edit(record)),button("Retire reference",()=>act({action:"retire",secret_id:record.id})));}row.append(actions);const versions=el("details");versions.append(el("summary","Version history"));for(const version of record.versions){const line=el("p",`Version ${version.version} · ${version.created_at} · ${version.destroyed?"Destroyed":version.deleted?"Deleted":"Available"}`);if(state.permissions.includes("admin")&&!version.destroyed)line.append(button(version.deleted?"Restore version":"Soft-delete version",()=>act({action:version.deleted?"restore_version":"delete_version",secret_id:record.id,version:version.version})));versions.append(line);}row.append(versions);for(const rotation of record.rotations){const line=el("p",`Device rotation: ${rotation.status}`);if(state.permissions.includes("rotate")&&!['completed','failed'].includes(rotation.status))line.append(button("Reconcile rotation",()=>act({action:"resume_rotation",secret_id:record.id,rotation_id:rotation.id})));row.append(line);}q("records").append(row);}if(!state.records.length)q("records").append(el("p","No credentials have been added for this enrollment."));}
async function act(body,{showValues=false}={}){if(busy)return;hide();busy=true;document.querySelectorAll("button").forEach(n=>n.disabled=true);try{if(!state)await load();const r=await fetch(base+"/action",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...body,nonce:state.nonce})});if(!r.ok)throw Error(await r.text());const result=await r.json();if(showValues&&!document.hidden){q("revealed").textContent=Object.entries(result.fields).map(([key,value])=>key+": "+value).join("\n");q("reveal").hidden=false;revealTimer=setTimeout(hide,30000);q("reveal").scrollIntoView({block:"nearest"});}message(result.message||(result.status?"Rotation: "+result.status:"Done"));await load();return result;}catch(e){message(e.message);try{await load();}catch{}}finally{busy=false;document.querySelectorAll("button").forEach(n=>n.disabled=false);render();}}
function renderFields(){q("fields").replaceChildren();for(const field of kinds[q("kind").value]){const label=el("label",field.replaceAll("-"," "));const input=el(field==="private-key"?"textarea":"input");input.dataset.field=field;input.autocomplete="off";if(input.tagName==="INPUT")input.type=["username","domain"].includes(field)?"text":"password";input.maxLength=32768;label.append(input);q("fields").append(label);}}
function fields(){return Object.fromEntries([...q("fields").querySelectorAll("[data-field]")].filter(n=>n.value).map(n=>[n.dataset.field,n.value]));}
function clearEditor(){q("credential-form").reset();q("fields").replaceChildren();q("editor").hidden=true;}
function edit(record){hide();q("record-id").value=record?.id||"";q("label").value=record?.label||"";q("kind").value=record?.kind||"rdp";q("kind").disabled=Boolean(record);q("editor-title").textContent=record?"Manage credential":"Add a credential";q("remote-binding").checked=Boolean(record?.use_for_remote);q("remote-choice").hidden=!record||!["rdp","ssh"].includes(record.kind);q("save-metadata").hidden=!record;q("save").textContent=record?"Save new vault version":"Save credential";q("rotate").hidden=!record||record.kind!=="rdp"||record.retired||!state.permissions.includes("rotate")||!state.endpoint_rotation_available;renderFields();q("editor").hidden=false;q("label").focus();}
q("kind").onchange=renderFields;q("cancel").onclick=clearEditor;q("add").onclick=()=>edit(null);q("refresh").onclick=()=>load().catch(e=>message(e.message));
q("credential-form").onsubmit=async event=>{event.preventDefault();const id=q("record-id").value;const body=id?{action:"replace",secret_id:id,expected_version:state.records.find(r=>r.id===id).current_version,fields:fields()}:{action:"create",request_id:crypto.randomUUID(),label:q("label").value,kind:q("kind").value,fields:fields()};clearEditor();await act(body);};
q("save-metadata").onclick=async()=>{const body={action:"edit",secret_id:q("record-id").value,label:q("label").value,use_for_remote:q("remote-binding").checked};clearEditor();await act(body);};
q("rotate").onclick=async()=>{const id=q("record-id").value;const body={action:"rotate",secret_id:id,rotation_id:crypto.randomUUID(),expected_version:state.records.find(r=>r.id===id).current_version,fields:fields()};clearEditor();await act(body);};
async function reveal(record){await act({action:"reveal",secret_id:record.id},{showValues:true});}
q("import-form").onsubmit=async event=>{event.preventDefault();const body={action:"import_recovery",job_id:q("recovery-job").value,label:q("import-label").value};q("import-label").value="";await act(body);};
load().catch(e=>message(e.message));
